{
	"version": 1710687738,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tombol_beranda-sheet0.png",
		"images/c-sheet0.png",
		"images/d-sheet0.png",
		"images/b-sheet0.png",
		"images/a-sheet0.png",
		"images/bg_0-sheet0.png",
		"images/pop-sheet0.png",
		"images/lirik_mijil-sheet0.png",
		"images/bg_5-sheet0.png",
		"images/madya-sheet0.png",
		"images/kw2-sheet0.png",
		"images/kw1-sheet0.png",
		"images/kaset-sheet0.png",
		"images/play-sheet0.png",
		"images/play-sheet1.png",
		"images/beranda-sheet0.png",
		"images/k1-sheet0.png",
		"images/k2-sheet0.png",
		"images/lirik_k1-sheet0.png",
		"images/lirik_k2-sheet0.png",
		"images/lirik_kw1-sheet0.png",
		"media/button.ogg",
		"media/select.ogg",
		"media/button.m4a",
		"media/select.m4a",
		"media/tombol.m4a",
		"media/tombol.ogg",
		"media/sub_lagu.m4a",
		"media/sub_lagu.ogg",
		"media/kawitan warga sari i.m4a",
		"media/kawitan warga sari i.ogg",
		"media/kawitan warga sari ii.m4a",
		"media/kawitan warga sari ii.ogg",
		"media/warga sari i.m4a",
		"media/warga sari i.ogg",
		"media/warga sari ii.m4a",
		"media/warga sari ii.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}